### ISSUE TITLE
用户重置密码，修改密码功能

### ISSUE THREAD

**Issue by ratlsun** [mock-api-agilean/issue-tracking#4]

**Comment by zhangxiaguang** [comment]
先做修改密码，后做忘记密码。

**Comment by zhangxiaguang** [comment]
<h4>1、修改密码：</h4>

用户登录后可自行修改密码；

<h4>2、忘记密码：</h4>

如果用户忘记密码可点击登录页面的“忘记密码”按钮，系统会将密码重置的链接发送到用户邮箱，用户可在2个自然日内点击密码重置链接来重置自己的密码。
