### ISSUE TITLE
支持public的模拟系统的创建

### ISSUE THREAD

**Issue by ratlsun** [mock-api-agilean/issue-tracking#7]
public模拟系统所有人可见
可以被关注
关注后能迅速查看该系统，但无法修改
应该能背快速搜索到

**Comment by zhangxiaguang** [comment]
#### 1、创建公共模拟器 <h4>

#### 2、非创建用户关注公共模拟器 <h4>

#### 3、非创建用户取消关注公共模拟器 <h4>

#### 4、非创建用户获取关注的公共模拟器并模拟运行 <h4>
